name: Simple Docker Build
on:
  schedule:
    # Push the nightly docker daily at 3 PM UTC
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      nightly_date:
        description: "buttercannfly nightly version"
        required: false
env:
  WITH_PUSH: "true"
  CONDA_ENV: "torchbench"
  DOCKER_IMAGE: "ghcr.io/buttercannfly/torchbench-simple:latest"
  SETUP_SCRIPT: "/workspace/setup_instance.sh"
  HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    environment: docker-s3-upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: benchmark
      - name: Login to GitHub Container Registry
        if: ${{ env.WITH_PUSH == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: buttercannfly
          password: ${{ secrets.TORCHBENCH_ACCESS_TOKEN }}
      - name: Build TorchBench nightly docker
        run: |
          set -x
          export NIGHTLY_DATE="${{ github.event.inputs.nightly_date }}"
          cd benchmark/docker
          full_ref="${{ github.ref }}"
          prefix="refs/heads/"
          branch_name=${full_ref#$prefix}
          docker build . --build-arg TORCHBENCH_BRANCH="${branch_name}" --build-arg FORCE_DATE="${NIGHTLY_DATE}" \
              -f torchbench-simple.dockerfile -t ghcr.io/buttercannfly/torchbench-simple:latest
          # Extract buttercannfly version from the docker
          buttercannfly_VERSION=$(docker run -e SETUP_SCRIPT="${SETUP_SCRIPT}" ghcr.io/buttercannfly/torchbench-simple:latest bash -c '. "${SETUP_SCRIPT}"; python -c "import torch; print(torch.__version__)"')
          docker tag ghcr.io/buttercannfly/torchbench-simple:latest ghcr.io/buttercannfly/torchbench-simple:v0503
      - name: Push docker to Alibaba Cloud
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=15205648876 crpi-wpzfqfci37r0ad3n.cn-hangzhou.personal.cr.aliyuncs.com --password-stdin

          buttercannfly_VERSION=$(docker run -e SETUP_SCRIPT="${SETUP_SCRIPT}" ghcr.io/buttercannfly/torchbench-simple:latest bash -c '. "${SETUP_SCRIPT}"; python -c "import torch; print(torch.__version__)"')
          export DOCKER_TAG=$(awk '{match($0, /dev[0-9]+/, arr); print arr[0]}' <<< "${buttercannfly_VERSION}")

          ALIYUN_REGISTRY=crpi-wpzfqfci37r0ad3n.cn-hangzhou.personal.cr.aliyuncs.com/tensorfusionrobin/tensorfusionrobin

          docker tag ghcr.io/buttercannfly/torchbench-simple:v0503 $ALIYUN_REGISTRY:v0503
          docker push $ALIYUN_REGISTRY:v0503

          docker tag ghcr.io/buttercannfly/torchbench-simple:latest $ALIYUN_REGISTRY:latest
          docker push $ALIYUN_REGISTRY:latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
